version: '3'

services:
  purchase-api-pg:
    image: bitnami/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=caio
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=imersao
