version: '3'

services:
  purchase-api-pg:
    image: bitnami/postgresql
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=caio
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=imersao
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
